server:
  port: 9001

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

management:
  security:
    enabled: false

spring:
  boot:
    admin:
      discovery:
        services: server-admin