server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: http://10.40.32.139:9092
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1
  boot:
    admin:
      client:
        url: http://10.40.32.139:9000
        instance:
          prefer-ip: true
  data:
    mongodb:
      uri: mongodb://sundarapandiank:Karnan22%40@cluster0-shard-00-00-vdmrr.mongodb.net:27017,cluster0-shard-00-01-vdmrr.mongodb.net:27017,cluster0-shard-00-02-vdmrr.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  path: C:/var/log/product-service/