server:
  port: 9001

spring:
  boot:
    admin:
      client:
        # url: http://${HOST_IP}:9000
        url: http://localhost:9000
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  path: C:/Users/kpaulpa/Documents/workArea/TechnicalWork/logs/blunt-onboard-service
