server:
  port: 9001

spring:
  boot:
    admin:
      discovery:
        services: server-admin

zuul:
  routes:
    account:
      path: /student/**
        serviceId: student-service

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health