spring:
  boot:
    admin:
      discovery:
        services: server-admin

management:
  security:
    enabled: false

zuul:
  routes:
    student:
      path: /student/**
      serviceId: student-service
    college:
      path: /college/**
      serviceId: college-service

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health