server:
  port: 8765

spring:
  kafka:
    bootstrap-servers: http://10.40.32.139:9092
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1
  boot:
    admin:
      client:
        url: http://10.40.32.139:9000
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
