server:
  port: 8765

spring:
  kafka:
    bootstrap-servers: http://35.237.201.4:9092
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1
  boot:
    admin:
      client:
        url: http://35.237.182.53:9000
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

zuul:
  routes:
    student:
      path: /student/**
      serviceId: student-service
    college:
      path: /college/**
      serviceId: college-service

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health