spring:
  boot:
    admin:
      discovery:
        services: server-admin

zuul:
  routes:
    student:
      path: /student/**
      serviceId: student-service
    college:
      path: /college/**
      serviceId: college-service

# http://192.168.1.4:9001/routes

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health