server:
  port: 8766

spring:
  kafka:
    bootstrap-servers: http://${HOST_IP}:9092
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
          name: admin-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false


logging:
  path: C:/var/log/gateway-service/test/