server:
  port: 9003

spring:
  boot:
    admin:
      discovery:
        services: server-admin

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health
