server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://35.237.182.53:9000
        instance:
          prefer-ip: true
  data:
    mongodb:
      uri: mongodb+srv://sundarapandiank:Karnan22%40@cluster0-vdmrr.mongodb.net/test?retryWrites=true
management:
  endpoints:
    web:
      exposure:
        include: "*"
