server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: http://10.40.32.70:9092
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1
  boot:
    admin:
      client:
        url: http://10.40.32.70:9000
        instance:
          prefer-ip: true
  data:
    mongodb:
      uri: mongodb+srv://sundarapandiank:Karnan22%40@cluster0-vdmrr.mongodb.net/test?retryWrites=true
management:
  endpoints:
    web:
      exposure:
        include: "*"

customer:
  title: title2

logging:
  path: C:/var/log/customer-service/